version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - postgre_db:/var/lib/postgresql/data

  backend:
    image: platonkara/foodgram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static_value:/backend_static/
      - media_value:/media/
    depends_on:
    - db

  frontend:
    image: platonkara/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_value:/frontend_static

  nginx:
    image: platonkara/foodgram_nginx
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  postgre_db:
  static_value:
  media_value:
